# Generated by Django 4.1.1 on 2022-09-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('subscribed', 'subscribed'), ('admin', 'admin')], default='user', max_length=200, verbose_name='Пользовательская роль'),
        ),
    ]
