# Generated by Django 2.2.16 on 2022-09-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(choices=[('user', 'user'), ('authorized', 'authorized'), ('admin', 'admin')], max_length=200, verbose_name='Пользовательское имя'),
        ),
    ]
